---
platform: linux

image_resource:
  type: docker-image
  source: {repository: sonarqube, tag: "latest"}

inputs:
- name: bantamweight

run:
  path: bantamweight/ci/tasks/sonarqube/run-sonarqube.sh
