groups:
- name: delivery
  jobs:
  - unit-tests

resources:
- name: bantamweight
  type: git
  source:
    uri: git@github.com:mcnichol/bantamweight.git
    branch: master
    private_key: {{ssh_private_key}}
jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: bantamweight
    trigger: true
  - task: run-unit-tests
    file: bantamweight/ci/run-unit-tests.yml