groups:
- name: delivery
  jobs:
  - unit-tests
  - sonarqube

resources:
- name: bantamweight
  type: git
  source:
    uri: git@github.com:mcnichol/bantamweight.git
    branch: master
    private_key: {{ssh_private_key}}

jobs:
- name: unit-tests
  serial: true
  plan:
  - get: bantamweight
    trigger: true
  - task: run-unit-tests
    file: bantamweight/ci/tasks/run-unit-tests.yml

- name: sonarqube
  plan:
  - get: bantamweight
    trigger: true
    passed: [unit-tests]
  - task: run-sonarqube
    file: bantamweight/ci/tasks/run-sonarqube.yml